theme: jekyll-theme-dinky
description: Dinky is a red hot theme for GitHub Pages.
nav:
    - Inicio: index.md
    - Capítulo 1: pagina2.md
links:
    - Name: Inicio
      url: /
    - Name: Página 2
      pagina2.md
    
